#set new commissions to list of currencies
POST http://{{host}}/api/commissions
Accept: application/json
Content-Type: application/json
Authorization: Basic admin password

{
  "commissionPt": 0,
  "from": "EUR",
  "to": "RUB"
}

###

#get all commissions
GET http://{{host}}/api/commissions
Content-Type: application/json
Authorization: Basic admin password

###
